mindmap
  root((Lancement produit))
    Recherche
      Entretiens clients
      Analyse du marché
      Positionnement
    Produit
      Prototype
      Tests utilisateurs
      Version 1.0
    Commercial
      Tarification
      Formation des ventes
      Partenariats
    Communication
      Site web
      Campagne de lancement
      Relations presse
    Mesure
      Adoption
      Rétention
      Satisfaction
