sankey-beta
Visiteurs,Page d'accueil,1000
Page d'accueil,Fiche produit,680
Page d'accueil,Sortie,320
Fiche produit,Panier,410
Fiche produit,Sortie,270
Panier,Paiement,300
Panier,Sortie,110
Paiement,Commande confirmee,245
Paiement,Echec,55
