---
config:
  treeView:
    showIcons: false
---
treeView-beta
  mermaid-preview-offline/
    src/
      extension.ts ## point d'entrée
      webview.ts :::highlight ## moteur de prévisualisation
      protocol.ts
    media/
      preview.css
      icon.png
    examples/
      README.md
    package.json ## manifeste de l'extension
    README.md
