railroad-beta
  title Grammaire d'une commande
  command = sequence(terminal("create"), nonterminal("identifier"), optional(terminal("--force")));
  identifier = sequence(nonterminal("letter"), zeroOrMore(choice(nonterminal("letter"), nonterminal("digit"), terminal("-"))));
  letter = choice(terminal("a"), terminal("b"), terminal("c"));
  digit = choice(terminal("0"), terminal("1"), terminal("2"));
