flowchart LR
  react@{ icon: "logos:react", form: "square", label: "React", pos: "b", h: 96 }
  node@{ icon: "logos:nodejs-icon", form: "square", label: "Node.js", pos: "b", h: 96 }
  database@{ icon: "material-icon-theme:database", form: "square", label: "Base de données", pos: "b", h: 96 }

  react --> node --> database
